//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace FeedEngine.com.morningstar.equityapi1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InvestorRelationsServiceSoap", Namespace="http://equityapi.morningstar.com/")]
    public partial class InvestorRelationsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SecurityHeader securityHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetCompanyEventCalendarOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompanyContactInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompanyGeneralInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBusinessDescriptionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InvestorRelationsService() {
            this.Url = global::FeedEngine.Properties.Settings.Default.FeedEngine_com_morningstar_equityapi1_InvestorRelationsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SecurityHeader SecurityHeaderValue {
            get {
                return this.securityHeaderValueField;
            }
            set {
                this.securityHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCompanyEventCalendarCompletedEventHandler GetCompanyEventCalendarCompleted;
        
        /// <remarks/>
        public event GetCompanyContactInformationCompletedEventHandler GetCompanyContactInformationCompleted;
        
        /// <remarks/>
        public event GetCompanyGeneralInformationCompletedEventHandler GetCompanyGeneralInformationCompleted;
        
        /// <remarks/>
        public event GetBusinessDescriptionCompletedEventHandler GetBusinessDescriptionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://equityapi.morningstar.com/GetCompanyEventCalendar", RequestNamespace="http://equityapi.morningstar.com/", ResponseNamespace="http://equityapi.morningstar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CompanyEventCalendars GetCompanyEventCalendar(string exchangeId, CompanyEventCalendarIdentifierType identifierType, string identifier, string startDate, string endDate) {
            object[] results = this.Invoke("GetCompanyEventCalendar", new object[] {
                        exchangeId,
                        identifierType,
                        identifier,
                        startDate,
                        endDate});
            return ((CompanyEventCalendars)(results[0]));
        }
        
        /// <remarks/>
        public void GetCompanyEventCalendarAsync(string exchangeId, CompanyEventCalendarIdentifierType identifierType, string identifier, string startDate, string endDate) {
            this.GetCompanyEventCalendarAsync(exchangeId, identifierType, identifier, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void GetCompanyEventCalendarAsync(string exchangeId, CompanyEventCalendarIdentifierType identifierType, string identifier, string startDate, string endDate, object userState) {
            if ((this.GetCompanyEventCalendarOperationCompleted == null)) {
                this.GetCompanyEventCalendarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompanyEventCalendarOperationCompleted);
            }
            this.InvokeAsync("GetCompanyEventCalendar", new object[] {
                        exchangeId,
                        identifierType,
                        identifier,
                        startDate,
                        endDate}, this.GetCompanyEventCalendarOperationCompleted, userState);
        }
        
        private void OnGetCompanyEventCalendarOperationCompleted(object arg) {
            if ((this.GetCompanyEventCalendarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompanyEventCalendarCompleted(this, new GetCompanyEventCalendarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://equityapi.morningstar.com/GetCompanyContactInformation", RequestNamespace="http://equityapi.morningstar.com/", ResponseNamespace="http://equityapi.morningstar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ContactInfos GetCompanyContactInformation(string exchangeId, ContactInfoIdentifierType identifierType, string identifier) {
            object[] results = this.Invoke("GetCompanyContactInformation", new object[] {
                        exchangeId,
                        identifierType,
                        identifier});
            return ((ContactInfos)(results[0]));
        }
        
        /// <remarks/>
        public void GetCompanyContactInformationAsync(string exchangeId, ContactInfoIdentifierType identifierType, string identifier) {
            this.GetCompanyContactInformationAsync(exchangeId, identifierType, identifier, null);
        }
        
        /// <remarks/>
        public void GetCompanyContactInformationAsync(string exchangeId, ContactInfoIdentifierType identifierType, string identifier, object userState) {
            if ((this.GetCompanyContactInformationOperationCompleted == null)) {
                this.GetCompanyContactInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompanyContactInformationOperationCompleted);
            }
            this.InvokeAsync("GetCompanyContactInformation", new object[] {
                        exchangeId,
                        identifierType,
                        identifier}, this.GetCompanyContactInformationOperationCompleted, userState);
        }
        
        private void OnGetCompanyContactInformationOperationCompleted(object arg) {
            if ((this.GetCompanyContactInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompanyContactInformationCompleted(this, new GetCompanyContactInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://equityapi.morningstar.com/GetCompanyGeneralInformation", RequestNamespace="http://equityapi.morningstar.com/", ResponseNamespace="http://equityapi.morningstar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CompanyInfos GetCompanyGeneralInformation(string exchangeId, CompanyInfoIdentifierType identifierType, string identifier) {
            object[] results = this.Invoke("GetCompanyGeneralInformation", new object[] {
                        exchangeId,
                        identifierType,
                        identifier});
            return ((CompanyInfos)(results[0]));
        }
        
        /// <remarks/>
        public void GetCompanyGeneralInformationAsync(string exchangeId, CompanyInfoIdentifierType identifierType, string identifier) {
            this.GetCompanyGeneralInformationAsync(exchangeId, identifierType, identifier, null);
        }
        
        /// <remarks/>
        public void GetCompanyGeneralInformationAsync(string exchangeId, CompanyInfoIdentifierType identifierType, string identifier, object userState) {
            if ((this.GetCompanyGeneralInformationOperationCompleted == null)) {
                this.GetCompanyGeneralInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompanyGeneralInformationOperationCompleted);
            }
            this.InvokeAsync("GetCompanyGeneralInformation", new object[] {
                        exchangeId,
                        identifierType,
                        identifier}, this.GetCompanyGeneralInformationOperationCompleted, userState);
        }
        
        private void OnGetCompanyGeneralInformationOperationCompleted(object arg) {
            if ((this.GetCompanyGeneralInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompanyGeneralInformationCompleted(this, new GetCompanyGeneralInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://equityapi.morningstar.com/GetBusinessDescription", RequestNamespace="http://equityapi.morningstar.com/", ResponseNamespace="http://equityapi.morningstar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BusinessDescriptions GetBusinessDescription(string exchangeId, BusinessDescriptionIdentifierType identifierType, string identifier) {
            object[] results = this.Invoke("GetBusinessDescription", new object[] {
                        exchangeId,
                        identifierType,
                        identifier});
            return ((BusinessDescriptions)(results[0]));
        }
        
        /// <remarks/>
        public void GetBusinessDescriptionAsync(string exchangeId, BusinessDescriptionIdentifierType identifierType, string identifier) {
            this.GetBusinessDescriptionAsync(exchangeId, identifierType, identifier, null);
        }
        
        /// <remarks/>
        public void GetBusinessDescriptionAsync(string exchangeId, BusinessDescriptionIdentifierType identifierType, string identifier, object userState) {
            if ((this.GetBusinessDescriptionOperationCompleted == null)) {
                this.GetBusinessDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBusinessDescriptionOperationCompleted);
            }
            this.InvokeAsync("GetBusinessDescription", new object[] {
                        exchangeId,
                        identifierType,
                        identifier}, this.GetBusinessDescriptionOperationCompleted, userState);
        }
        
        private void OnGetBusinessDescriptionOperationCompleted(object arg) {
            if ((this.GetBusinessDescriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBusinessDescriptionCompleted(this, new GetBusinessDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://equityapi.morningstar.com/", IsNullable=false)]
    public partial class SecurityHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string tokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public partial class Item {
        
        private string languageCodeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public partial class BusinessDescriptionItem {
        
        private Item[] shortDescriptionField;
        
        private Item[] mediumDescriptionField;
        
        private Item[] longDescriptionField;
        
        /// <remarks/>
        public Item[] ShortDescription {
            get {
                return this.shortDescriptionField;
            }
            set {
                this.shortDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public Item[] MediumDescription {
            get {
                return this.mediumDescriptionField;
            }
            set {
                this.mediumDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public Item[] LongDescription {
            get {
                return this.longDescriptionField;
            }
            set {
                this.longDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public partial class BusinessDescriptionEntity {
        
        private string companyNameField;
        
        private string exchangeIdField;
        
        private string symbolField;
        
        private string cUSIPField;
        
        private string cIKField;
        
        private string iSINField;
        
        private string sEDOLField;
        
        private string shortDescriptionField;
        
        private string mediumDescriptionField;
        
        private string longDescriptionField;
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string ExchangeId {
            get {
                return this.exchangeIdField;
            }
            set {
                this.exchangeIdField = value;
            }
        }
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string CUSIP {
            get {
                return this.cUSIPField;
            }
            set {
                this.cUSIPField = value;
            }
        }
        
        /// <remarks/>
        public string CIK {
            get {
                return this.cIKField;
            }
            set {
                this.cIKField = value;
            }
        }
        
        /// <remarks/>
        public string ISIN {
            get {
                return this.iSINField;
            }
            set {
                this.iSINField = value;
            }
        }
        
        /// <remarks/>
        public string SEDOL {
            get {
                return this.sEDOLField;
            }
            set {
                this.sEDOLField = value;
            }
        }
        
        /// <remarks/>
        public string ShortDescription {
            get {
                return this.shortDescriptionField;
            }
            set {
                this.shortDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string MediumDescription {
            get {
                return this.mediumDescriptionField;
            }
            set {
                this.mediumDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LongDescription {
            get {
                return this.longDescriptionField;
            }
            set {
                this.longDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public partial class BusinessDescriptions {
        
        private Message messageInfoField;
        
        private GeneralInfoEntity generalInfoField;
        
        private BusinessDescriptionEntity businessDescriptionEntityField;
        
        private BusinessDescriptionItem businessDescriptionField;
        
        /// <remarks/>
        public Message MessageInfo {
            get {
                return this.messageInfoField;
            }
            set {
                this.messageInfoField = value;
            }
        }
        
        /// <remarks/>
        public GeneralInfoEntity GeneralInfo {
            get {
                return this.generalInfoField;
            }
            set {
                this.generalInfoField = value;
            }
        }
        
        /// <remarks/>
        public BusinessDescriptionEntity BusinessDescriptionEntity {
            get {
                return this.businessDescriptionEntityField;
            }
            set {
                this.businessDescriptionEntityField = value;
            }
        }
        
        /// <remarks/>
        public BusinessDescriptionItem BusinessDescription {
            get {
                return this.businessDescriptionField;
            }
            set {
                this.businessDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public partial class Message {
        
        private int messageCodeField;
        
        private string messageDetailField;
        
        /// <remarks/>
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MessageDetail {
            get {
                return this.messageDetailField;
            }
            set {
                this.messageDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public partial class GeneralInfoEntity {
        
        private string shareClassIdField;
        
        private string companyNameField;
        
        private string exchangeIdField;
        
        private string symbolField;
        
        private string cUSIPField;
        
        private string cIKField;
        
        private string iSINField;
        
        private string sEDOLField;
        
        /// <remarks/>
        public string ShareClassId {
            get {
                return this.shareClassIdField;
            }
            set {
                this.shareClassIdField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string ExchangeId {
            get {
                return this.exchangeIdField;
            }
            set {
                this.exchangeIdField = value;
            }
        }
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string CUSIP {
            get {
                return this.cUSIPField;
            }
            set {
                this.cUSIPField = value;
            }
        }
        
        /// <remarks/>
        public string CIK {
            get {
                return this.cIKField;
            }
            set {
                this.cIKField = value;
            }
        }
        
        /// <remarks/>
        public string ISIN {
            get {
                return this.iSINField;
            }
            set {
                this.iSINField = value;
            }
        }
        
        /// <remarks/>
        public string SEDOL {
            get {
                return this.sEDOLField;
            }
            set {
                this.sEDOLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public partial class CompanyInfoEntity {
        
        private string companyStatusField;
        
        private string statusTypeField;
        
        private string localNameField;
        
        private string localNameLanguageCodeField;
        
        private string shortNameField;
        
        private string businessCountryField;
        
        private string domicileCountryField;
        
        private string placeOfInCorporationField;
        
        private System.Nullable<int> yearEstablishedField;
        
        private bool yearEstablishedFieldSpecified;
        
        private System.Nullable<int> fiscalYearEndField;
        
        private bool fiscalYearEndFieldSpecified;
        
        private System.Nullable<bool> isREITField;
        
        private bool isREITFieldSpecified;
        
        private System.Nullable<bool> isShellField;
        
        private bool isShellFieldSpecified;
        
        private System.Nullable<bool> isLimitedPartnershipField;
        
        private bool isLimitedPartnershipFieldSpecified;
        
        private string operationStatusField;
        
        private string webAddressField;
        
        private string addressLanguageCodeField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressLine3Field;
        
        private string addressLine4Field;
        
        private string cityField;
        
        private string stateField;
        
        private string countryField;
        
        private string postalCodeField;
        
        private string phoneField;
        
        private string faxField;
        
        private System.Nullable<int> totalEmployeeField;
        
        private bool totalEmployeeFieldSpecified;
        
        private System.Nullable<int> partTimeField;
        
        private bool partTimeFieldSpecified;
        
        private System.Nullable<int> fullTimeField;
        
        private bool fullTimeFieldSpecified;
        
        private string auditorField;
        
        private string legalAdvisorField;
        
        private string industryIdField;
        
        private string industryNameField;
        
        private string industryGroupIdField;
        
        private string industryGroupNameField;
        
        private string sectorIdField;
        
        private string sectorNameField;
        
        private System.Nullable<int> uSASICField;
        
        private bool uSASICFieldSpecified;
        
        private System.Nullable<int> uSASIC1Field;
        
        private bool uSASIC1FieldSpecified;
        
        private System.Nullable<int> uSASIC2Field;
        
        private bool uSASIC2FieldSpecified;
        
        private System.Nullable<int> uSASIC3Field;
        
        private bool uSASIC3FieldSpecified;
        
        private System.Nullable<int> uSASIC4Field;
        
        private bool uSASIC4FieldSpecified;
        
        private System.Nullable<int> uSASIC5Field;
        
        private bool uSASIC5FieldSpecified;
        
        private System.Nullable<int> uSASIC6Field;
        
        private bool uSASIC6FieldSpecified;
        
        private System.Nullable<int> uSASIC7Field;
        
        private bool uSASIC7FieldSpecified;
        
        private System.Nullable<int> uSASIC8Field;
        
        private bool uSASIC8FieldSpecified;
        
        private System.Nullable<int> uSASIC9Field;
        
        private bool uSASIC9FieldSpecified;
        
        private System.Nullable<int> uSASIC10Field;
        
        private bool uSASIC10FieldSpecified;
        
        private System.Nullable<int> cANSICField;
        
        private bool cANSICFieldSpecified;
        
        private System.Nullable<int> cANSIC1Field;
        
        private bool cANSIC1FieldSpecified;
        
        private System.Nullable<int> cANSIC2Field;
        
        private bool cANSIC2FieldSpecified;
        
        private System.Nullable<int> cANSIC3Field;
        
        private bool cANSIC3FieldSpecified;
        
        private System.Nullable<int> cANSIC4Field;
        
        private bool cANSIC4FieldSpecified;
        
        private System.Nullable<int> cANSIC5Field;
        
        private bool cANSIC5FieldSpecified;
        
        private System.Nullable<int> cANSIC6Field;
        
        private bool cANSIC6FieldSpecified;
        
        private System.Nullable<int> cANSIC7Field;
        
        private bool cANSIC7FieldSpecified;
        
        private System.Nullable<int> cANSIC8Field;
        
        private bool cANSIC8FieldSpecified;
        
        private System.Nullable<int> cANSIC9Field;
        
        private bool cANSIC9FieldSpecified;
        
        private System.Nullable<int> cANSIC10Field;
        
        private bool cANSIC10FieldSpecified;
        
        private System.Nullable<int> nAICSField;
        
        private bool nAICSFieldSpecified;
        
        private System.Nullable<int> nAICS1Field;
        
        private bool nAICS1FieldSpecified;
        
        private System.Nullable<int> nAICS2Field;
        
        private bool nAICS2FieldSpecified;
        
        private System.Nullable<int> nAICS3Field;
        
        private bool nAICS3FieldSpecified;
        
        private System.Nullable<int> nAICS4Field;
        
        private bool nAICS4FieldSpecified;
        
        private System.Nullable<int> nAICS5Field;
        
        private bool nAICS5FieldSpecified;
        
        private System.Nullable<int> nAICS6Field;
        
        private bool nAICS6FieldSpecified;
        
        private System.Nullable<int> nAICS7Field;
        
        private bool nAICS7FieldSpecified;
        
        private System.Nullable<int> nAICS8Field;
        
        private bool nAICS8FieldSpecified;
        
        private System.Nullable<int> nAICS9Field;
        
        private bool nAICS9FieldSpecified;
        
        private System.Nullable<int> nAICS10Field;
        
        private bool nAICS10FieldSpecified;
        
        /// <remarks/>
        public string CompanyStatus {
            get {
                return this.companyStatusField;
            }
            set {
                this.companyStatusField = value;
            }
        }
        
        /// <remarks/>
        public string StatusType {
            get {
                return this.statusTypeField;
            }
            set {
                this.statusTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LocalName {
            get {
                return this.localNameField;
            }
            set {
                this.localNameField = value;
            }
        }
        
        /// <remarks/>
        public string LocalNameLanguageCode {
            get {
                return this.localNameLanguageCodeField;
            }
            set {
                this.localNameLanguageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessCountry {
            get {
                return this.businessCountryField;
            }
            set {
                this.businessCountryField = value;
            }
        }
        
        /// <remarks/>
        public string DomicileCountry {
            get {
                return this.domicileCountryField;
            }
            set {
                this.domicileCountryField = value;
            }
        }
        
        /// <remarks/>
        public string PlaceOfInCorporation {
            get {
                return this.placeOfInCorporationField;
            }
            set {
                this.placeOfInCorporationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> YearEstablished {
            get {
                return this.yearEstablishedField;
            }
            set {
                this.yearEstablishedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearEstablishedSpecified {
            get {
                return this.yearEstablishedFieldSpecified;
            }
            set {
                this.yearEstablishedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FiscalYearEnd {
            get {
                return this.fiscalYearEndField;
            }
            set {
                this.fiscalYearEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FiscalYearEndSpecified {
            get {
                return this.fiscalYearEndFieldSpecified;
            }
            set {
                this.fiscalYearEndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsREIT {
            get {
                return this.isREITField;
            }
            set {
                this.isREITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsREITSpecified {
            get {
                return this.isREITFieldSpecified;
            }
            set {
                this.isREITFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsShell {
            get {
                return this.isShellField;
            }
            set {
                this.isShellField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsShellSpecified {
            get {
                return this.isShellFieldSpecified;
            }
            set {
                this.isShellFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsLimitedPartnership {
            get {
                return this.isLimitedPartnershipField;
            }
            set {
                this.isLimitedPartnershipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsLimitedPartnershipSpecified {
            get {
                return this.isLimitedPartnershipFieldSpecified;
            }
            set {
                this.isLimitedPartnershipFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string OperationStatus {
            get {
                return this.operationStatusField;
            }
            set {
                this.operationStatusField = value;
            }
        }
        
        /// <remarks/>
        public string WebAddress {
            get {
                return this.webAddressField;
            }
            set {
                this.webAddressField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLanguageCode {
            get {
                return this.addressLanguageCodeField;
            }
            set {
                this.addressLanguageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine3 {
            get {
                return this.addressLine3Field;
            }
            set {
                this.addressLine3Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine4 {
            get {
                return this.addressLine4Field;
            }
            set {
                this.addressLine4Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TotalEmployee {
            get {
                return this.totalEmployeeField;
            }
            set {
                this.totalEmployeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalEmployeeSpecified {
            get {
                return this.totalEmployeeFieldSpecified;
            }
            set {
                this.totalEmployeeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PartTime {
            get {
                return this.partTimeField;
            }
            set {
                this.partTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartTimeSpecified {
            get {
                return this.partTimeFieldSpecified;
            }
            set {
                this.partTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FullTime {
            get {
                return this.fullTimeField;
            }
            set {
                this.fullTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FullTimeSpecified {
            get {
                return this.fullTimeFieldSpecified;
            }
            set {
                this.fullTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Auditor {
            get {
                return this.auditorField;
            }
            set {
                this.auditorField = value;
            }
        }
        
        /// <remarks/>
        public string LegalAdvisor {
            get {
                return this.legalAdvisorField;
            }
            set {
                this.legalAdvisorField = value;
            }
        }
        
        /// <remarks/>
        public string IndustryId {
            get {
                return this.industryIdField;
            }
            set {
                this.industryIdField = value;
            }
        }
        
        /// <remarks/>
        public string IndustryName {
            get {
                return this.industryNameField;
            }
            set {
                this.industryNameField = value;
            }
        }
        
        /// <remarks/>
        public string IndustryGroupId {
            get {
                return this.industryGroupIdField;
            }
            set {
                this.industryGroupIdField = value;
            }
        }
        
        /// <remarks/>
        public string IndustryGroupName {
            get {
                return this.industryGroupNameField;
            }
            set {
                this.industryGroupNameField = value;
            }
        }
        
        /// <remarks/>
        public string SectorId {
            get {
                return this.sectorIdField;
            }
            set {
                this.sectorIdField = value;
            }
        }
        
        /// <remarks/>
        public string SectorName {
            get {
                return this.sectorNameField;
            }
            set {
                this.sectorNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> USASIC {
            get {
                return this.uSASICField;
            }
            set {
                this.uSASICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USASICSpecified {
            get {
                return this.uSASICFieldSpecified;
            }
            set {
                this.uSASICFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> USASIC1 {
            get {
                return this.uSASIC1Field;
            }
            set {
                this.uSASIC1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USASIC1Specified {
            get {
                return this.uSASIC1FieldSpecified;
            }
            set {
                this.uSASIC1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> USASIC2 {
            get {
                return this.uSASIC2Field;
            }
            set {
                this.uSASIC2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USASIC2Specified {
            get {
                return this.uSASIC2FieldSpecified;
            }
            set {
                this.uSASIC2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> USASIC3 {
            get {
                return this.uSASIC3Field;
            }
            set {
                this.uSASIC3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USASIC3Specified {
            get {
                return this.uSASIC3FieldSpecified;
            }
            set {
                this.uSASIC3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> USASIC4 {
            get {
                return this.uSASIC4Field;
            }
            set {
                this.uSASIC4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USASIC4Specified {
            get {
                return this.uSASIC4FieldSpecified;
            }
            set {
                this.uSASIC4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> USASIC5 {
            get {
                return this.uSASIC5Field;
            }
            set {
                this.uSASIC5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USASIC5Specified {
            get {
                return this.uSASIC5FieldSpecified;
            }
            set {
                this.uSASIC5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> USASIC6 {
            get {
                return this.uSASIC6Field;
            }
            set {
                this.uSASIC6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USASIC6Specified {
            get {
                return this.uSASIC6FieldSpecified;
            }
            set {
                this.uSASIC6FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> USASIC7 {
            get {
                return this.uSASIC7Field;
            }
            set {
                this.uSASIC7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USASIC7Specified {
            get {
                return this.uSASIC7FieldSpecified;
            }
            set {
                this.uSASIC7FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> USASIC8 {
            get {
                return this.uSASIC8Field;
            }
            set {
                this.uSASIC8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USASIC8Specified {
            get {
                return this.uSASIC8FieldSpecified;
            }
            set {
                this.uSASIC8FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> USASIC9 {
            get {
                return this.uSASIC9Field;
            }
            set {
                this.uSASIC9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USASIC9Specified {
            get {
                return this.uSASIC9FieldSpecified;
            }
            set {
                this.uSASIC9FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> USASIC10 {
            get {
                return this.uSASIC10Field;
            }
            set {
                this.uSASIC10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USASIC10Specified {
            get {
                return this.uSASIC10FieldSpecified;
            }
            set {
                this.uSASIC10FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CANSIC {
            get {
                return this.cANSICField;
            }
            set {
                this.cANSICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANSICSpecified {
            get {
                return this.cANSICFieldSpecified;
            }
            set {
                this.cANSICFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CANSIC1 {
            get {
                return this.cANSIC1Field;
            }
            set {
                this.cANSIC1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANSIC1Specified {
            get {
                return this.cANSIC1FieldSpecified;
            }
            set {
                this.cANSIC1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CANSIC2 {
            get {
                return this.cANSIC2Field;
            }
            set {
                this.cANSIC2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANSIC2Specified {
            get {
                return this.cANSIC2FieldSpecified;
            }
            set {
                this.cANSIC2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CANSIC3 {
            get {
                return this.cANSIC3Field;
            }
            set {
                this.cANSIC3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANSIC3Specified {
            get {
                return this.cANSIC3FieldSpecified;
            }
            set {
                this.cANSIC3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CANSIC4 {
            get {
                return this.cANSIC4Field;
            }
            set {
                this.cANSIC4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANSIC4Specified {
            get {
                return this.cANSIC4FieldSpecified;
            }
            set {
                this.cANSIC4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CANSIC5 {
            get {
                return this.cANSIC5Field;
            }
            set {
                this.cANSIC5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANSIC5Specified {
            get {
                return this.cANSIC5FieldSpecified;
            }
            set {
                this.cANSIC5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CANSIC6 {
            get {
                return this.cANSIC6Field;
            }
            set {
                this.cANSIC6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANSIC6Specified {
            get {
                return this.cANSIC6FieldSpecified;
            }
            set {
                this.cANSIC6FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CANSIC7 {
            get {
                return this.cANSIC7Field;
            }
            set {
                this.cANSIC7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANSIC7Specified {
            get {
                return this.cANSIC7FieldSpecified;
            }
            set {
                this.cANSIC7FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CANSIC8 {
            get {
                return this.cANSIC8Field;
            }
            set {
                this.cANSIC8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANSIC8Specified {
            get {
                return this.cANSIC8FieldSpecified;
            }
            set {
                this.cANSIC8FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CANSIC9 {
            get {
                return this.cANSIC9Field;
            }
            set {
                this.cANSIC9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANSIC9Specified {
            get {
                return this.cANSIC9FieldSpecified;
            }
            set {
                this.cANSIC9FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CANSIC10 {
            get {
                return this.cANSIC10Field;
            }
            set {
                this.cANSIC10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANSIC10Specified {
            get {
                return this.cANSIC10FieldSpecified;
            }
            set {
                this.cANSIC10FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NAICS {
            get {
                return this.nAICSField;
            }
            set {
                this.nAICSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAICSSpecified {
            get {
                return this.nAICSFieldSpecified;
            }
            set {
                this.nAICSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NAICS1 {
            get {
                return this.nAICS1Field;
            }
            set {
                this.nAICS1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAICS1Specified {
            get {
                return this.nAICS1FieldSpecified;
            }
            set {
                this.nAICS1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NAICS2 {
            get {
                return this.nAICS2Field;
            }
            set {
                this.nAICS2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAICS2Specified {
            get {
                return this.nAICS2FieldSpecified;
            }
            set {
                this.nAICS2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NAICS3 {
            get {
                return this.nAICS3Field;
            }
            set {
                this.nAICS3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAICS3Specified {
            get {
                return this.nAICS3FieldSpecified;
            }
            set {
                this.nAICS3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NAICS4 {
            get {
                return this.nAICS4Field;
            }
            set {
                this.nAICS4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAICS4Specified {
            get {
                return this.nAICS4FieldSpecified;
            }
            set {
                this.nAICS4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NAICS5 {
            get {
                return this.nAICS5Field;
            }
            set {
                this.nAICS5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAICS5Specified {
            get {
                return this.nAICS5FieldSpecified;
            }
            set {
                this.nAICS5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NAICS6 {
            get {
                return this.nAICS6Field;
            }
            set {
                this.nAICS6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAICS6Specified {
            get {
                return this.nAICS6FieldSpecified;
            }
            set {
                this.nAICS6FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NAICS7 {
            get {
                return this.nAICS7Field;
            }
            set {
                this.nAICS7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAICS7Specified {
            get {
                return this.nAICS7FieldSpecified;
            }
            set {
                this.nAICS7FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NAICS8 {
            get {
                return this.nAICS8Field;
            }
            set {
                this.nAICS8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAICS8Specified {
            get {
                return this.nAICS8FieldSpecified;
            }
            set {
                this.nAICS8FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NAICS9 {
            get {
                return this.nAICS9Field;
            }
            set {
                this.nAICS9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAICS9Specified {
            get {
                return this.nAICS9FieldSpecified;
            }
            set {
                this.nAICS9FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NAICS10 {
            get {
                return this.nAICS10Field;
            }
            set {
                this.nAICS10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAICS10Specified {
            get {
                return this.nAICS10FieldSpecified;
            }
            set {
                this.nAICS10FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public partial class CompanyInfos {
        
        private Message messageInfoField;
        
        private GeneralInfoEntity generalInfoField;
        
        private CompanyInfoEntity companyInfoEntityField;
        
        /// <remarks/>
        public Message MessageInfo {
            get {
                return this.messageInfoField;
            }
            set {
                this.messageInfoField = value;
            }
        }
        
        /// <remarks/>
        public GeneralInfoEntity GeneralInfo {
            get {
                return this.generalInfoField;
            }
            set {
                this.generalInfoField = value;
            }
        }
        
        /// <remarks/>
        public CompanyInfoEntity CompanyInfoEntity {
            get {
                return this.companyInfoEntityField;
            }
            set {
                this.companyInfoEntityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public partial class ContactInfoEntity {
        
        private string companyNameField;
        
        private string exchangeIdField;
        
        private string symbolField;
        
        private string cUSIPField;
        
        private string cIKField;
        
        private string iSINField;
        
        private string sEDOLField;
        
        private string contactPersonNameField;
        
        private string professionalTitleField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string provinceField;
        
        private string countryField;
        
        private string postalCodeField;
        
        private string phone1Field;
        
        private string phone2Field;
        
        private string faxField;
        
        private string emailAddressField;
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string ExchangeId {
            get {
                return this.exchangeIdField;
            }
            set {
                this.exchangeIdField = value;
            }
        }
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string CUSIP {
            get {
                return this.cUSIPField;
            }
            set {
                this.cUSIPField = value;
            }
        }
        
        /// <remarks/>
        public string CIK {
            get {
                return this.cIKField;
            }
            set {
                this.cIKField = value;
            }
        }
        
        /// <remarks/>
        public string ISIN {
            get {
                return this.iSINField;
            }
            set {
                this.iSINField = value;
            }
        }
        
        /// <remarks/>
        public string SEDOL {
            get {
                return this.sEDOLField;
            }
            set {
                this.sEDOLField = value;
            }
        }
        
        /// <remarks/>
        public string ContactPersonName {
            get {
                return this.contactPersonNameField;
            }
            set {
                this.contactPersonNameField = value;
            }
        }
        
        /// <remarks/>
        public string ProfessionalTitle {
            get {
                return this.professionalTitleField;
            }
            set {
                this.professionalTitleField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
            }
        }
        
        /// <remarks/>
        public string Phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public partial class ContactInfos {
        
        private Message messageInfoField;
        
        private GeneralInfoEntity generalInfoField;
        
        private ContactInfoEntity contactInfoEntityField;
        
        /// <remarks/>
        public Message MessageInfo {
            get {
                return this.messageInfoField;
            }
            set {
                this.messageInfoField = value;
            }
        }
        
        /// <remarks/>
        public GeneralInfoEntity GeneralInfo {
            get {
                return this.generalInfoField;
            }
            set {
                this.generalInfoField = value;
            }
        }
        
        /// <remarks/>
        public ContactInfoEntity ContactInfoEntity {
            get {
                return this.contactInfoEntityField;
            }
            set {
                this.contactInfoEntityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public partial class CompanyEventCalendarEntity {
        
        private string eventNameField;
        
        private string eventTypeField;
        
        private string eventURLField;
        
        private string timeZoneField;
        
        private System.Nullable<System.DateTime> beginDateTimeField;
        
        private bool beginDateTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> endDateTimeField;
        
        private bool endDateTimeFieldSpecified;
        
        /// <remarks/>
        public string EventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
            }
        }
        
        /// <remarks/>
        public string EventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
            }
        }
        
        /// <remarks/>
        public string EventURL {
            get {
                return this.eventURLField;
            }
            set {
                this.eventURLField = value;
            }
        }
        
        /// <remarks/>
        public string TimeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> BeginDateTime {
            get {
                return this.beginDateTimeField;
            }
            set {
                this.beginDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BeginDateTimeSpecified {
            get {
                return this.beginDateTimeFieldSpecified;
            }
            set {
                this.beginDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EndDateTime {
            get {
                return this.endDateTimeField;
            }
            set {
                this.endDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateTimeSpecified {
            get {
                return this.endDateTimeFieldSpecified;
            }
            set {
                this.endDateTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public partial class CompanyEventCalendars {
        
        private Message messageInfoField;
        
        private GeneralInfoEntity generalInfoField;
        
        private CompanyEventCalendarEntity[] companyEventCalendarEntityListField;
        
        /// <remarks/>
        public Message MessageInfo {
            get {
                return this.messageInfoField;
            }
            set {
                this.messageInfoField = value;
            }
        }
        
        /// <remarks/>
        public GeneralInfoEntity GeneralInfo {
            get {
                return this.generalInfoField;
            }
            set {
                this.generalInfoField = value;
            }
        }
        
        /// <remarks/>
        public CompanyEventCalendarEntity[] CompanyEventCalendarEntityList {
            get {
                return this.companyEventCalendarEntityListField;
            }
            set {
                this.companyEventCalendarEntityListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public enum CompanyEventCalendarIdentifierType {
        
        /// <remarks/>
        Symbol,
        
        /// <remarks/>
        CUSIP,
        
        /// <remarks/>
        ISIN,
        
        /// <remarks/>
        SEDOL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public enum ContactInfoIdentifierType {
        
        /// <remarks/>
        Symbol,
        
        /// <remarks/>
        CUSIP,
        
        /// <remarks/>
        ISIN,
        
        /// <remarks/>
        SEDOL,
        
        /// <remarks/>
        CIK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public enum CompanyInfoIdentifierType {
        
        /// <remarks/>
        Symbol,
        
        /// <remarks/>
        CUSIP,
        
        /// <remarks/>
        ISIN,
        
        /// <remarks/>
        SEDOL,
        
        /// <remarks/>
        CIK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equityapi.morningstar.com/")]
    public enum BusinessDescriptionIdentifierType {
        
        /// <remarks/>
        Symbol,
        
        /// <remarks/>
        CUSIP,
        
        /// <remarks/>
        ISIN,
        
        /// <remarks/>
        SEDOL,
        
        /// <remarks/>
        CIK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCompanyEventCalendarCompletedEventHandler(object sender, GetCompanyEventCalendarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompanyEventCalendarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompanyEventCalendarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompanyEventCalendars Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompanyEventCalendars)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCompanyContactInformationCompletedEventHandler(object sender, GetCompanyContactInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompanyContactInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompanyContactInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ContactInfos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ContactInfos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCompanyGeneralInformationCompletedEventHandler(object sender, GetCompanyGeneralInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompanyGeneralInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompanyGeneralInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompanyInfos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompanyInfos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetBusinessDescriptionCompletedEventHandler(object sender, GetBusinessDescriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBusinessDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBusinessDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BusinessDescriptions Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BusinessDescriptions)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591